<a href="https://colab.research.google.com/github/YuliaCherniakova/python-basic_alg_const/blob/main/numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A=np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
A=np.ones(10)
print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
A=[5]*10
print(A)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [ ]:
A=np.arange(10,51)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
A=np.arange(10,51,2)
print(A)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
A=np.array([[0,1,2], [3,4,5], [6,7,8]])
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
A=np.ones([3,3])
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import random
random.random()

0.40627898861960376

In [ ]:
np.random.randn(25)

array([ 1.64828687, -2.42200468, -0.47182866,  0.37281   , -0.83721627,
       -0.16540214, -0.11530873,  0.52864194,  1.83562621,  1.46359199,
        1.73286492,  0.31095103, -0.25983955, -0.24906703,  0.63401655,
       -1.40213032,  0.890067  , -0.31406831,  0.54375906,  1.5085167 ,
        0.53970791,  0.19462825,  0.33948068,  0.58496803, -1.60061004])

In [ ]:
A=np.arange(0.01,1.01,0.01).reshape(10,10)
print(A)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat[(2,3,4),1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat[3,4])

20


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat[0:3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat[4])

[21 22 23 24 25]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat[(3,4),:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat.sum())

325


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat.sum(axis=0))

[55 60 65 70 75]
